/**
 * Shared, framework-agnostic constants: database/table identifiers and the
 * enumerations used across the data model. Imported by both the SvelteKit app
 * (via `$lib/constants`) and the standalone provisioning script.
 */

export const DATABASE_ID = 'main';
export const PHOTO_BUCKET_ID = 'profile_photos';
export const SUBMISSION_IMAGE_BUCKET_ID = 'submission_images';
export const FEEDBACK_BUCKET_ID = 'feedback_uploads';

export const TABLES = {
	users: 'users',
	profiles: 'profiles',
	submissions: 'writing_submissions',
	events: 'events',
	rewardsRules: 'rewards_rules',
	activityLogs: 'activity_logs',
	badges: 'badges',
	userBadges: 'user_badges',
	siteSettings: 'site_settings',
	feedback: 'feedback'
};

export const ROLES = ['member', 'admin'];
export const USER_STATUSES = ['pending', 'active', 'suspended'];

export const CONTENT_TYPES = [
	'blog',
	'essay',
	'article',
	'excerpt',
	'newsletter',
	'research',
	'book',
	'other'
];
export const SUBMISSION_STATUSES = ['pending', 'approved', 'rejected', 'featured'];

export const EVENT_SOURCES = ['luma', 'manual'];

export const BADGE_CRITERIA = [
	'profile_completion',
	'submissions',
	'featured',
	'content_types',
	'active_months'
];

/**
 * Fallback cover for a piece with no uploaded image and no scrapable OG image.
 * Distinct from the site-wide /og.png so a coverless piece doesn't masquerade as
 * the front page. Generated by scripts/make-og.mjs.
 */
export const DEFAULT_SUBMISSION_IMAGE = '/writing-placeholder.png';

export const FEEDBACK_CATEGORIES = ['bug', 'idea', 'question', 'other'];
export const FEEDBACK_STATUSES = ['new', 'reviewed', 'resolved'];

/** Plain-language labels so non-technical members recognise their situation. */
export const FEEDBACK_CATEGORY_LABELS = {
	bug: 'Something looks broken',
	idea: 'An idea or suggestion',
	question: 'A question',
	other: 'Something else'
};

/** Human-friendly labels for content types, reused across the UI. */
export const CONTENT_TYPE_LABELS = {
	blog: 'Blog',
	essay: 'Essay',
	article: 'Article',
	excerpt: 'Excerpt',
	newsletter: 'Newsletter',
	research: 'Research',
	book: 'Book',
	other: 'Other'
};

/** A curated set of writing genres offered as suggestions during onboarding. */
export const GENRE_SUGGESTIONS = [
	'Fiction',
	'Literary Fiction',
	'Poetry',
	'Essays',
	'Memoir',
	'Long-form Nonfiction',
	'Journalism',
	'Newsletter',
	'Blogging',
	'Screenwriting',
	'Speculative Fiction',
	'Travel Writing',
	'Food Writing',
	'Technical Writing',
	'Copywriting',
	'Children’s Writing'
];

/**
 * Outbound email runs through Appwrite Messaging with the Resend adapter. The
 * organiser's inbox is both the reply-to (set on the provider) and a CC on
 * every email so member replies and copies land in one place. The sender is
 * the verified Resend domain address. Override per environment with
 * MESSAGING_FROM_EMAIL / MESSAGING_FROM_NAME / MESSAGING_REPLY_TO / MESSAGING_CC.
 */
export const MESSAGING = {
	providerId: 'resend',
	providerName: 'Resend',
	fromName: "The Writers' Room BLR",
	fromEmail: 'team@thewritersroom.club',
	replyTo: 'adityaoberai1@gmail.com',
	cc: 'adityaoberai1@gmail.com'
};

/** site_settings keys holding the admin-editable welcome email copy. */
export const WELCOME_EMAIL_SETTING_KEYS = {
	subject: 'welcome_email_subject',
	body: 'welcome_email_body'
};

/** Default welcome email, seeded into site_settings and used when the setting is blank. */
export const WELCOME_EMAIL_DEFAULTS = {
	subject: "Welcome to The Writers' Room BLR",
	body: `Hi there,

Thank you for signing up for The Writers' Room BLR. It's good to have you in the room.

Before we meet, we'd love to know a little about you. Just hit reply and tell us:

1. Have you written a blog before?
2. Have you attended a past Writers' Room event?
3. Do you live in Bengaluru, or visit from time to time?

A line or two on each is plenty. We read every reply.

See you at the next session,
The Writers' Room BLR`
};
